server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/alvin_mall?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password:  # 你的数据库密码
  druid:
    initial-size: 10
    min-idle: 10
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionErrorRetryAttempts: 3
    breakAfterAcquireFailure: true
    timeBetweenConnectErrorMillis: 300000
    asyncInit: true
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    transaction-query-timeout: 6000
    filters: stat,wall,log4j2
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    web-stat-filter:
      enabled: true
      url-pattern: "/*"
      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    stat-view-servlet:
      url-pattern: "/druid/*"
      allow:
      deny:
      reset-enable: false
      login-username: admin
      login-password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  database: alvin-mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90
    common: 86400


logstash:
  host: localhost
  enableInnerLog: false